{% set version = '1.1.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-semantic.assets
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/semantic.assets_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/semantic.assets/semantic.assets_{{ version }}.tar.gz
  sha256: 47d715e0c8d01ca04e3832cf8551fcf3c27ed02bc88df801a30df197977e1300

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-htmlwidgets
  run:
    - r-base
    - r-htmlwidgets

test:
  commands:
    - $R -e "library('semantic.assets')"           # [not win]
    - "\"%R%\" -e \"library('semantic.assets')\""  # [win]

about:
  home: https://github.com/Appsilon/semantic.assets
  license: LGPL-3.0-only
  summary: Style sheets and JavaScript assets for 'shiny.semantic' package.
  license_family: LGPL
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
